# write a program to input eight number
#  from the user and display all
# the unique number(ones)
s = set()
i = input("enter a number1:")
s.add(i)
i = input("enter a number2:")
s.add(i)
i = input("enter a number3:")
s.add(i)
i = input("enter a number4:")
s.add(i)
i = input("enter a number5:")
s.add(i)
i = input("enter a number6:")
s.add(i)
i = input("enter a number7:")
s.add(i)
i = input("enter a number8:")
s.add(i)
print("unique number:", s)